version: '3'

services:

  server:
    image: cockroachdb/cockroach:v19.2.2
    environment:
      COCKROACHDB_USER: ${DB_USERNAME:-upperio_user}
      COCKROACHDB_DB: ${DB_NAME:-upperio}
    command: "start --insecure"
    ports:
      - "26257:26257"
      - "8080:8080"